# NumPy

In [1]:
# import as a library
import numpy as np  #使用前先打np.

In [2]:
# 一維陣列
A = np.array([1,2,3])
A

array([1, 2, 3])

In [3]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

row 橫列
column 直行

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
# 二維陣列
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
A + A

array([2, 4, 6])

In [7]:
A * 5        # vector內元素重複五次

array([ 5, 10, 15])

In [8]:
A * A

array([1, 4, 9])

In [9]:
B = np.array([[1],[2],[3]])
B

array([[1],
       [2],
       [3]])

In [10]:
A * B

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [11]:
np.arange(0,10)  #建立等距的矩陣

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)  # np.arrange(start, end, step), start及step可省略

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.arange(77)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.eye(4) #單位矩陣

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# 數值平均分布的陣列
np.linspace(0, 5, 10)    # np.linspace(start, end, 個數)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.linspace(5, 10) # np.linspace(start, end, 個數)省略開始，會變成兩數相乘的數量

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [19]:
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
data[0] #第一個[]是0，接續1、2、3.....

array([1, 2, 3, 4])

In [21]:
data[1, 3] #看第25列，行列順序都是0開始，0、1、2、3

8

因為內建會顯示False，還是會是顯示默認的，所以一定要打inplace

In [22]:
# same as del df['new']
df.drop('new',axis=1, inplace = True ) # inplace = False by default 永久置換
df

NameError: name 'df' is not defined

# Exercise

1. 利用下面的資料建立DataFrame <br/>
list1 = [[90, 60, 33], [50, 70, 75], [70, 90, 88], [80, 50, 60]] <br/>
columns = ['Math', 'English', 'History'] <br/>
index=['Simon','Allen','Jimmy','Peter']

In [47]:
list1 = [[90, 60, 33], [50, 70, 75], [70, 90, 88], [80, 50, 60]]
columns = ['Math', 'English', 'History']
index=['Simon','Allen','Jimmy','Peter']
np.array([[90, 60, 33], [50, 70, 75], [70, 90, 88], [80, 50, 60]])

array([[90, 60, 33],
       [50, 70, 75],
       [70, 90, 88],
       [80, 50, 60]])

In [48]:
import pandas as pd

In [49]:
df = pd.DataFrame(data= [[90, 60, 33], [50, 70, 75], [70, 90, 88], [80, 50, 60]],columns='Math English History'.split(),index='Simon Allen Jimmy Peter'.split())
df

Math  English  History
Simon    90       60       33
Allen    50       70       75
Jimmy    70       90       88
Peter    80       50       60

取出數學>60 且英文>85 的資料, 並以DataFrame的方式呈現

In [50]:
df[df['Math']>60]

Math  English  History
Simon    90       60       33
Jimmy    70       90       88
Peter    80       50       60

In [51]:
df[df['English']>85]

Math  English  History
Jimmy    70       90       88

計算各科的平均數

In [52]:
df.mean()

Math       72.5
English    67.5
History    64.0
dtype: float64

依各科分數來個別排名

In [53]:
df.rank()

Math  English  History
Simon   4.0      2.0      1.0
Allen   1.0      3.0      3.0
Jimmy   2.0      4.0      4.0
Peter   3.0      1.0      2.0

新增性別資料
Gender = ['M'.'F','M','M']

In [54]:
Man='M'
Female='F'

In [55]:
df['Gender'] = ['M','F','M','M']
df

Math  English  History Gender
Simon    90       60       33      M
Allen    50       70       75      F
Jimmy    70       90       88      M
Peter    80       50       60      M

性別的類別各出現幾次？

In [56]:
cute=pd.value_counts(['M','F','M','M'])
cute

M    3
F    1
dtype: int64

算出每位同學的平均分數，再用平均分數排名

In [57]:
df['mean']=df.mean(1)
df

Math  English  History Gender       mean
Simon    90       60       33      M  61.000000
Allen    50       70       75      F  65.000000
Jimmy    70       90       88      M  82.666667
Peter    80       50       60      M  63.333333

In [59]:
df.sort_values(by=['mean'])

Math  English  History Gender       mean
Simon    90       60       33      M  61.000000
Peter    80       50       60      M  63.333333
Allen    50       70       75      F  65.000000
Jimmy    70       90       88      M  82.666667